### ISSUE TITLE
404 (Not Found)

### ISSUE THREAD

**Issue by JoshuaCE** [itprosolutions/aurelia-bootstrap-datepicker#1]
Hello, im facing this issue.

The CSS file imported as JS, can you please help to fix it.

_http://localhost:9000/jspm_packages/npm/aurelia-bootstrap-datepicker@0.0.7/**aurelia-bootstrap-datepicker.css.js** 404 (Not Found)_

**Comment by Tseberechts** [comment]
Fixed in

**Comment by Tseberechts** [comment]
Fixed in 0.0.8
